### ISSUE TITLE
Winner determined incorrectly

### ISSUE THREAD

**Issue by lidavidm** [HaliteChallenge/Halite-III#148]
https://forums.halite.io/t/bug-in-suiciding-on-home-with-halite-for-final-move/901

**Comment by lidavidm** [comment]
Another example: https://forums.halite.io/t/anyone-know-how-the-winner-was-determined-here/903

**Comment by 0Zeta** [comment]
From the halite Website: "If a player does not have a ship or enough energy to construct a ship, they are considered “dead” and lose the game." Probably the game ends because of both players having no ships left before the dropped halite is added to the player´s halite amount. But indeed changing the game logic so the other player would have won the game would make sense.

**Comment by lidavidm** [comment]
@0Zeta yup, pretty much. Fix is simple enough but needs some testing.
