### ISSUE TITLE
Segfault when issuing commands to nonexistent ships

### ISSUE THREAD

**Issue by lidavidm** [HaliteChallenge/Halite-III#22]
Found by ChatTor on Discord:

```
Anyway, I found a seg fault in the halite executable for Linux and am not sure what causes it. I can reproduce it with the following:
Round 1: Send g\n\n 
Round 2: Send g\nm 0 s\n\n 
It seems to seg fault immediately after that
```

**Comment by Janzert** [comment]
It's crashing because it triggers the assert at line 25 of `core/Store.cpp` and looks to be in the code path that checks that you actually own the ship you're trying to move. An abreviated stack trace is something like, starting from `process_turn()` line 235 of `HaliteImpl.cpp`, going through `CommandTransaction.cpp` line 98 `add_command`, then `CommandTransaction.cpp` line 16 `check_ownership`.

It seems that trying to move any non-existent ship id will trigger it. Either one that is already dead or hasn't been spawned yet. So a check that a ship exists before trying to check ownership should fix it. But I'm not familiar with this area so may be misreading the code.
