### ISSUE TITLE
add map height/width to constants

### ISSUE THREAD

**Issue by snaar** [HaliteChallenge/Halite-III#78]
Then add "normalize" function to position class.

**Comment by YoavRamon** [comment]
game_map instance (from game.game_map) has height and width values

**Comment by snaar** [comment]
Sure, but it's inconvenient. For example if you want to do any sort of normalization outside of game_map class, you have to pass height and width around. It's a lot nicer to have them as constants since they don't change during the game anyway.

**Comment by anuzis** [comment]
height and width are not constants, though. They are configuration parameters which change depending on the size of the map. Indeed it would be inconvenient to pass them around everywhere. A good solution is passing them once and storing them as class attributes in whichever class handles your AI decisions.

e.g. My implementation has a HiveAI class which gets initialized with the GameMap and stores HiveAI.map_width and HiveAI.map_height so the values are easily accessible to any ShipAI (or anything else) relating to where decisions are made which may want to know width and height.

**Comment by snaar** [comment]
We already have max_turns in constants. That also depends on size of the map. Storing them locally is fine, but then would you really double the size of position objects so that they can have height/width along with x/y so that positions can self-normalize? Seems a bit excessive.

**Comment by anuzis** [comment]
Good point on precedent with max_turns, and having height and width in constants is likely higher utility to have easily accessible.

Agreed height/width shouldn't be duplicated in every Position instance (instantiation of which is already in my bot's top 5 time consuming activities via cProfile since Positions are used so often). Adding a normalization method to positions would also be convenient.

It might even be nice to normalize Position instances automatically at the time they're instantiated, since why would anyone ever prefer a non-normalized Position? Only downside is the extra processing, and Python devs are already at a relative disadvantage there.

**Comment by coreylowman** [comment]
Actually isn't equality broken for all starter kits since normalization isn't done automatically in any of them?

```
>>> Position(0, 0) == Position(32, 32)
False
>>> game_map.normalize(Position(0, 0)) == game_map.normalize(Position(32, 32))
True
```

Isn't that a huge issue? Path planning depends hugely on skipping already checked positions. if people aren't using normalized positions then their path planning is doing a huge amount of extra work.

**Comment by snaar** [comment]
Python has work-around pushed via https://github.com/HaliteChallenge/Halite-III/pull/176
