### ISSUE TITLE
[python starter kit] Move class Player out of game_map.py into player.py

### ISSUE THREAD

**Issue by anuzis** [HaliteChallenge/Halite-III#83]
If the Python starter kit is intended as the most accessible for aspiring AI developers, it's eventually worth moving the Player class out of game_map.py and into its own file.

At this stage of the competition it may temporarily create some backwards compatibility issues if anyone is importing the Player class from game_map, but that's unlikely to be a significant issue because:

1. There was no need to import Player anywhere in my first 20+ hours on my Python submission. The instance is accessible easily enough via game.Me and there's little reason for developers to actually import it.
2. Considering the above, anyone who 1) has found the Player class hiding in game_map.py, and 2) imports it into one of their files for whatever reason ==> is likely savvy enough with Python to immediately understand and fix the import error in under ~5-10 seconds if they need to shift it in their own code.

ref: https://github.com/HaliteChallenge/Halite-III/blob/master/starter_kits/Python3/hlt/game_map.py#L9

**Comment by snaar** [comment]
There are no backwards compatibility issues, since everyone copies a starter kit when they start working. The only issue is that documentation needs to be updated to reflect any changes like that. But being able to change starter kits freely without having backwards compatibility issues is by design.

I'm ok with this change.
